# Generated by Django 3.2.8 on 2021-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('revision', models.IntegerField()),
                ('file_guid', models.CharField(max_length=1000)),
            ],
        ),
    ]
